export default defineEventHandler(async (event) => {
  console.log(event)
  return await event.context.cf
})



// {
//   __is_event__: true,
//   node:
//    { req:
//       IncomingMessage {
//         _events: [Object],
//         _readableState: [ReadableState],
//         _maxListeners: undefined,
//         socket: [Socket],
//         httpVersionMajor: 1,
//         httpVersionMinor: 1,
//         httpVersion: '1.1',
//         complete: true,
//         rawHeaders: [Array],
//         rawTrailers: [],
//         joinDuplicateHeaders: null,
//         aborted: false,
//         upgrade: false,
//         url: '/api/cf-headers-test',
//         method: 'GET',
//         statusCode: null,
//         statusMessage: null,
//         client: [Socket],
//         _consuming: false,
//         _dumped: false,
//         originalUrl: '/api/cf-headers-test',
//         __unenv__: [Object],
//         [Symbol(shapeMode)]: true,
//         [Symbol(kCapture)]: false,
//         [Symbol(kHeaders)]: [Object],
//         [Symbol(kHeadersCount)]: 40,
//         [Symbol(kTrailers)]: null,
//         [Symbol(kTrailersCount)]: 0 },
//      res:
//       ServerResponse {
//         _events: [Object: null prototype],
//         _eventsCount: 1,
//         _maxListeners: undefined,
//         outputData: [],
//         outputSize: 0,
//         writable: true,
//         destroyed: false,
//         _last: false,
//         chunkedEncoding: false,
//         shouldKeepAlive: false,
//         maxRequestsOnConnectionReached: false,
//         _defaultKeepAlive: true,
//         useChunkedEncodingByDefault: true,
//         sendDate: true,
//         _removedConnection: false,
//         _removedContLen: false,
//         _removedTE: false,
//         strictContentLength: false,
//         _contentLength: null,
//         _hasBody: true,
//         _trailer: '',
//         finished: false,
//         _headerSent: false,
//         _closed: false,
//         _header: null,
//         _keepAliveTimeout: 5000,
//         _onPendingData: [Function: bound updateOutgoingData],
//         req: [IncomingMessage],
//         _sent100: false,
//         _expect_continue: false,
//         _maxRequestsPerSocket: 0,
//         [Symbol(shapeMode)]: false,
//         [Symbol(kCapture)]: false,
//         [Symbol(kBytesWritten)]: 0,
//         [Symbol(kNeedDrain)]: false,
//         [Symbol(corked)]: 0,
//         [Symbol(kChunkedBuffer)]: [],
//         [Symbol(kChunkedLength)]: 0,
//         [Symbol(kSocket)]: [Socket],
//         [Symbol(kOutHeaders)]: [Object: null prototype],
//         [Symbol(errored)]: null,
//         [Symbol(kHighWaterMark)]: 65536,
//         [Symbol(kRejectNonStandardBodyWrites)]: false,
//         [Symbol(kUniqueHeaders)]: null } },
//   web: undefined,
//   context:
//    { nitro: { errors: [] },
//      cf:
//       { clientTcpRtt: 16,
//         requestHeaderNames: {},
//         httpProtocol: 'HTTP/1.1',
//         tlsCipher: 'AEAD-AES256-GCM-SHA384',
//         continent: 'AS',
//         asn: 45609,
//         clientAcceptEncoding: 'br, gzip, deflate',
//         country: 'IN',
//         verifiedBotCategory: '',
//         tlsClientAuth: [Object],
//         tlsClientExtensionsSha1: 'Y7DIC8A6G0/aXviZ8ie/xDbJb7g=',
//         tlsExportedAuthenticator: [Object],
//         tlsVersion: 'TLSv1.3',
//         city: 'Bengaluru',
//         timezone: 'Asia/Kolkata',
//         requestPriority: '',
//         region: 'Karnataka',
//         edgeRequestKeepAliveStatus: 1,
//         tlsClientRandom: '+LPVQVcU8QsKmRyzmxKkZV4xtb2fzjAQA/XOHGMrQLo=',
//         longitude: '77.59100',
//         latitude: '12.97530',
//         postalCode: '562130',
//         regionCode: 'KA',
//         asOrganization: 'Airtel',
//         tlsClientHelloLength: '386',
//         colo: 'BLR',
//         botManagement: [Object] },
//      waitUntil: [Function: bound waitUntil],
//      cloudflare:
//       { request:
//          Request { method: 'GET',
//            url: 'http://localhost:3000/api/cf-headers-test',
//            headers: Headers {},
//            destination: '',
//            referrer: 'about:client',
//            referrerPolicy: '',
//            mode: 'cors',
//            credentials: 'same-origin',
//            cache: 'default',
//            redirect: 'follow',
//            integrity: '',
//            keepalive: false,
//            isReloadNavigation: false,
//            isHistoryNavigation: false,
//            signal: AbortSignal { aborted: false } },
//         env: [Object],
//         context: ExecutionContext {} },
//      _nitro: { routeRules: [Object] },
//      matchedRoute: { path: '/api/cf-headers-test', handlers: [Object] },
//      params: {} },
//   _method: 'GET',
//   _path: '/api/cf-headers-test',
//   _headers: undefined,
//   _requestBody: undefined,
//   _handled: false,
//   _onBeforeResponseCalled: undefined,
//   _onAfterResponseCalled: undefined,
//   fetch: [Function (anonymous)],
//   '$fetch': [Function (anonymous)],
//   waitUntil: [Function (anonymous)],
//   captureError: [Function (anonymous)] }
